export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAILED = 'GET_USERS_FAILED'

export const DASHBOARD_SUCCESS = 'DASHBOARD_SUCCESS'
export const DASHBOARD_FAILED = 'DASHBOARD_FAILED'

export const GET_HOLIDAYS_LIST_SUCCESS = 'GET_HOLIDAYS_LIST_SUCCESS'
export const GET_HOLIDAYS_LIST_FAILED = 'GET_HOLIDAYS_LIST_FAILED'
export const GET_HOLIDAY_SUCCESS = 'GET_HOLIDAY_SUCCESS'
export const GET_HOLIDAY_FAILED = 'GET_HOLIDAY_FAILED'
export const CREATE_HOLIDAY_SUCCESS = 'CREATE_HOLIDAY_SUCCESS'
export const CREATE_HOLIDAY_FAILED = 'CREATE_HOLIDAY_FAILED'
export const UPDATE_HOLIDAY_SUCCESS = 'UPDATE_HOLIDAY_SUCCESS'
export const UPDATE_HOLIDAY_FAILED = 'UPDATE_HOLIDAY_FAILED'
export const DELETE_HOLIDAY_SUCCESS = 'DELETE_HOLIDAY_SUCCESS'
export const DELETE_HOLIDAY_FAILED = 'DELETE_HOLIDAY_FAILED'

// $Generator: New Action Type Constants Here
